# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: computer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='computer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x63omputer.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x8c\x01\n\x08\x43omputer\x12 \n\nSquareRoot\x12\x07.Number\x1a\x07.Number\"\x00\x12\x1e\n\x06Primes\x12\x07.Number\x1a\x07.Number\"\x00\x30\x01\x12\x1b\n\x03STD\x12\x07.Number\x1a\x07.Number\"\x00(\x01\x12!\n\x07MaxElem\x12\x07.Number\x1a\x07.Number\"\x00(\x01\x30\x01\x62\x06proto3'
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Number.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=41,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'computer_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  })
_sym_db.RegisterMessage(Number)



_COMPUTER = _descriptor.ServiceDescriptor(
  name='Computer',
  full_name='Computer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=44,
  serialized_end=184,
  methods=[
  _descriptor.MethodDescriptor(
    name='SquareRoot',
    full_name='Computer.SquareRoot',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Primes',
    full_name='Computer.Primes',
    index=1,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='STD',
    full_name='Computer.STD',
    index=2,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MaxElem',
    full_name='Computer.MaxElem',
    index=3,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPUTER)

DESCRIPTOR.services_by_name['Computer'] = _COMPUTER

# @@protoc_insertion_point(module_scope)
